### PR TITLE
Update Axum example to use axum 0.7 and hyper 1.

### PR DESCRIPTION
**Pull request by TannerRogalsky**
The internals of the various components of this example have changed significantly. While this works, I'd appreciate a careful review to ensure that it is correct in addition to functional.

Thank you!

### CODE REVIEW

**Comment by TannerRogalsky** [comment]
The hyper-util dependency has been updated to the most recent release. I believe this is good to merge now baring any review change requests.

**Comment by getong** [comment]
@TannerRogalsky 
How about taking a look at the grpc example, which might be updated too?

**Comment by TannerRogalsky** [comment]
@getong I'm not interested in doing that but you should be able to use my code an example of the things that need to change.

**Comment by getong** [comment]
> @getong I'm not interested in doing that but you should be able to use my code an example of the things that need to change.

I am willing to do this, I tried but failed, I does not know how to fix it.

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
